[9.0][NEW] connector_prestashop_feature: New module
guewen/connector-prestashop pull request #8
Opened 2016-11-29 17:34 UTC by sergio-teruel

This PR allow import PS features, the module depends from product_custom_info (Repository: product-attributes)

2016-12-05 11:10 UTC, guewen requested changes

2016-12-05 11:10 UTC, guewen commented on connector_prestashop_feature/connector.py
> +    _name = 'connector_prestashop_feature.installed'
you don't need this "virtual" model.

2016-12-05 11:10 UTC, guewen commented on connector_prestashop_feature/models/custom_info_option/importer.py
> +        # self._import_feature()
Is it normal that it is not called?

2016-12-05 11:10 UTC, guewen commented on connector_prestashop_feature/models/product_template/importer.py
> +@prestashop(replacing=importer.ProductTemplateImporter)
This will be an issue the day we'll have 2 addons that try to replace importer.ProductTemplateImporter.

2018-06-28 18:57 UTC, pedrobaeza commented
@sergio-teruel I think we should discard these PRs.

2019-03-07 15:52 UTC, rafaelbn commented
@sergio-teruel what do you think about closing this PRs?

This too could be closed: https://github.com/guewen/connector-prestashop/pull/9

2019-08-28 22:12 UTC, rafaelbn commented
This PR can be closed

2019-09-13 18:17 UTC, closed without merging